/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThesisRouteImport } from './routes/thesis'
import { Route as StandardRouteImport } from './routes/standard'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as InvitationRouteImport } from './routes/invitation'
import { Route as FutureRouteImport } from './routes/future'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as BuildRouteImport } from './routes/build'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectorSlugRouteImport } from './routes/sector.$slug'

const ThesisRoute = ThesisRouteImport.update({
  id: '/thesis',
  path: '/thesis',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardRoute = StandardRouteImport.update({
  id: '/standard',
  path: '/standard',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationRoute = InvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorSlugRoute = SectorSlugRouteImport.update({
  id: '/sector/$slug',
  path: '/sector/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/ecosystem': typeof EcosystemRoute
  '/future': typeof FutureRoute
  '/invitation': typeof InvitationRoute
  '/journal': typeof JournalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/standard': typeof StandardRoute
  '/thesis': typeof ThesisRoute
  '/sector/$slug': typeof SectorSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/ecosystem': typeof EcosystemRoute
  '/future': typeof FutureRoute
  '/invitation': typeof InvitationRoute
  '/journal': typeof JournalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/standard': typeof StandardRoute
  '/thesis': typeof ThesisRoute
  '/sector/$slug': typeof SectorSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/ecosystem': typeof EcosystemRoute
  '/future': typeof FutureRoute
  '/invitation': typeof InvitationRoute
  '/journal': typeof JournalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/standard': typeof StandardRoute
  '/thesis': typeof ThesisRoute
  '/sector/$slug': typeof SectorSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/build'
    | '/ecosystem'
    | '/future'
    | '/invitation'
    | '/journal'
    | '/sitemap.xml'
    | '/standard'
    | '/thesis'
    | '/sector/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/build'
    | '/ecosystem'
    | '/future'
    | '/invitation'
    | '/journal'
    | '/sitemap.xml'
    | '/standard'
    | '/thesis'
    | '/sector/$slug'
  id:
    | '__root__'
    | '/'
    | '/build'
    | '/ecosystem'
    | '/future'
    | '/invitation'
    | '/journal'
    | '/sitemap.xml'
    | '/standard'
    | '/thesis'
    | '/sector/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildRoute: typeof BuildRoute
  EcosystemRoute: typeof EcosystemRoute
  FutureRoute: typeof FutureRoute
  InvitationRoute: typeof InvitationRoute
  JournalRoute: typeof JournalRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StandardRoute: typeof StandardRoute
  ThesisRoute: typeof ThesisRoute
  SectorSlugRoute: typeof SectorSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thesis': {
      id: '/thesis'
      path: '/thesis'
      fullPath: '/thesis'
      preLoaderRoute: typeof ThesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standard': {
      id: '/standard'
      path: '/standard'
      fullPath: '/standard'
      preLoaderRoute: typeof StandardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation': {
      id: '/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof InvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sector/$slug': {
      id: '/sector/$slug'
      path: '/sector/$slug'
      fullPath: '/sector/$slug'
      preLoaderRoute: typeof SectorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildRoute: BuildRoute,
  EcosystemRoute: EcosystemRoute,
  FutureRoute: FutureRoute,
  InvitationRoute: InvitationRoute,
  JournalRoute: JournalRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StandardRoute: StandardRoute,
  ThesisRoute: ThesisRoute,
  SectorSlugRoute: SectorSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
